
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author melik
 */
public class ArkaBölüm extends javax.swing.JFrame {
    
    public ArkaBölüm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        lblArkaBölüm_YapýlmakÝstenen = new javax.swing.JLabel();
        lblResim_Pasta = new javax.swing.JLabel();
        lblResim_Kek = new javax.swing.JLabel();
        lbl_Pasta = new javax.swing.JLabel();
        lbl_Kek = new javax.swing.JLabel();
        lbl_Kadayýf = new javax.swing.JLabel();
        chcArkaBölüm_pasta = new javax.swing.JCheckBox();
        chcArkaBölüm_Kek = new javax.swing.JCheckBox();
        chcArkaBölüm_Kadayýf = new javax.swing.JCheckBox();
        btnArkaBölüm_PastaTarifAlýþveriþ = new javax.swing.JButton();
        btnArkaBölüm_KekTarifAlýþveriþ = new javax.swing.JButton();
        btnArkaBölüm_KadayýfTarifAlýþveriþ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblArkaBölüm_YapýlmakÝstenen.setBackground(new java.awt.Color(0, 0, 0));
        lblArkaBölüm_YapýlmakÝstenen.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        lblArkaBölüm_YapýlmakÝstenen.setForeground(new java.awt.Color(255, 0, 51));
        lblArkaBölüm_YapýlmakÝstenen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArkaBölüm_YapýlmakÝstenen.setText("Bugün ne yapmak istiyorsun ?");
        lblArkaBölüm_YapýlmakÝstenen.setToolTipText("");
        lblArkaBölüm_YapýlmakÝstenen.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Soru :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(0, 51, 255))); // NOI18N
        lblArkaBölüm_YapýlmakÝstenen.setOpaque(true);
        jPanel3.add(lblArkaBölüm_YapýlmakÝstenen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 57));

        lblResim_Pasta.setBackground(new java.awt.Color(153, 153, 153));
        lblResim_Pasta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/pasta.jpg"))); // NOI18N
        lblResim_Pasta.setOpaque(true);
        jPanel3.add(lblResim_Pasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 112, 104, -1));

        lblResim_Kek.setBackground(new java.awt.Color(153, 153, 153));
        lblResim_Kek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/kek.jpg"))); // NOI18N
        lblResim_Kek.setText("jLabel2");
        lblResim_Kek.setOpaque(true);
        jPanel3.add(lblResim_Kek, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 239, 112, -1));

        lbl_Pasta.setBackground(new java.awt.Color(204, 204, 255));
        lbl_Pasta.setText("Pasta");
        lbl_Pasta.setDisplayedMnemonicIndex(2);
        lbl_Pasta.setOpaque(true);
        jPanel3.add(lbl_Pasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 143, 146, 37));

        lbl_Kek.setBackground(new java.awt.Color(204, 204, 255));
        lbl_Kek.setText("Kek");
        lbl_Kek.setDisplayedMnemonicIndex(2);
        lbl_Kek.setOpaque(true);
        jPanel3.add(lbl_Kek, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 259, 146, 39));

        lbl_Kadayýf.setBackground(new java.awt.Color(204, 204, 255));
        lbl_Kadayýf.setText("Kadayýf");
        lbl_Kadayýf.setOpaque(true);
        jPanel3.add(lbl_Kadayýf, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 369, 146, 36));

        buttonGroup1.add(chcArkaBölüm_pasta);
        jPanel3.add(chcArkaBölüm_pasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 152, 22, -1));

        buttonGroup1.add(chcArkaBölüm_Kek);
        jPanel3.add(chcArkaBölüm_Kek, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 269, 22, -1));

        buttonGroup1.add(chcArkaBölüm_Kadayýf);
        jPanel3.add(chcArkaBölüm_Kadayýf, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 381, 22, -1));

        btnArkaBölüm_PastaTarifAlýþveriþ.setText("Pasta tarifi ve alýþveriþ");
        btnArkaBölüm_PastaTarifAlýþveriþ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArkaBölüm_PastaTarifAlýþveriþActionPerformed(evt);
            }
        });
        jPanel3.add(btnArkaBölüm_PastaTarifAlýþveriþ, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 142, 221, 40));

        btnArkaBölüm_KekTarifAlýþveriþ.setText("Kek tarifi ve alýþveriþ");
        btnArkaBölüm_KekTarifAlýþveriþ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArkaBölüm_KekTarifAlýþveriþActionPerformed(evt);
            }
        });
        jPanel3.add(btnArkaBölüm_KekTarifAlýþveriþ, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 256, 221, 45));

        btnArkaBölüm_KadayýfTarifAlýþveriþ.setText("Kadayýf tarifi ve alýþveriþ");
        btnArkaBölüm_KadayýfTarifAlýþveriþ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArkaBölüm_KadayýfTarifAlýþveriþActionPerformed(evt);
            }
        });
        jPanel3.add(btnArkaBölüm_KadayýfTarifAlýþveriþ, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 367, 221, 41));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/kadayýf.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 367, 116, 76));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/master2.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArkaBölüm_PastaTarifAlýþveriþActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArkaBölüm_PastaTarifAlýþveriþActionPerformed
        
        if((chcArkaBölüm_pasta.isSelected() == true)){ // //chcArkaBölüm_pasta ADINDAKI CHECKBOX'UMUZUN SEÇÝLÝ OLUP OLMADIGINI BOOLEAN IFADE ILE KONTROL EDER 
            TarifVeAlýþveriþ alýþveriþ = new TarifVeAlýþveriþ();
            alýþveriþ.setVisible(true);
            this.setVisible(false);
        }
        else 
            JOptionPane.showMessageDialog(rootPane, "TARÝF VE ALIÞVERÝÞ KISMINA ULAÞMAK ÝÇÝN ÝLGÝLÝ ALANI SEÇÝN");
        
    }//GEN-LAST:event_btnArkaBölüm_PastaTarifAlýþveriþActionPerformed

    private void btnArkaBölüm_KekTarifAlýþveriþActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArkaBölüm_KekTarifAlýþveriþActionPerformed
        if((chcArkaBölüm_Kek.isSelected() == true)){   //chcArkaBölüm_Kek ADINDAKI CHECKBOX'UMUZUN SEÇÝLÝ OLUP OLMADIGINI BOOLEAN IFADE ILE KONTROL EDER 
             TarifVeAlýþveriþ_2 alýþveriþ2 = new TarifVeAlýþveriþ_2(); 
             alýþveriþ2.setVisible(true);
             this.setVisible(false);
        }
        else 
            JOptionPane.showMessageDialog(rootPane, "TARÝF VE ALIÞVERÝÞ KISMINA ULAÞMAK ÝÇÝN ÝLGÝLÝ ALANI SEÇÝN");
    }//GEN-LAST:event_btnArkaBölüm_KekTarifAlýþveriþActionPerformed

    private void btnArkaBölüm_KadayýfTarifAlýþveriþActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArkaBölüm_KadayýfTarifAlýþveriþActionPerformed
       if((chcArkaBölüm_Kadayýf.isSelected() == true)){
             TarifVeAlýþveriþ_3 alýþveriþ3 = new TarifVeAlýþveriþ_3(); 
             alýþveriþ3.setVisible(true);
             this.setVisible(false);
        }
        else 
            JOptionPane.showMessageDialog(rootPane, "TARÝF VE ALIÞVERÝÞ KISMINA ULAÞMAK ÝÇÝN ÝLGÝLÝ ALANI SEÇÝN");
    }//GEN-LAST:event_btnArkaBölüm_KadayýfTarifAlýþveriþActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArkaBölüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArkaBölüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArkaBölüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArkaBölüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArkaBölüm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArkaBölüm_KadayýfTarifAlýþveriþ;
    private javax.swing.JButton btnArkaBölüm_KekTarifAlýþveriþ;
    private javax.swing.JButton btnArkaBölüm_PastaTarifAlýþveriþ;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chcArkaBölüm_Kadayýf;
    private javax.swing.JCheckBox chcArkaBölüm_Kek;
    private javax.swing.JCheckBox chcArkaBölüm_pasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblArkaBölüm_YapýlmakÝstenen;
    private javax.swing.JLabel lblResim_Kek;
    private javax.swing.JLabel lblResim_Pasta;
    private javax.swing.JLabel lbl_Kadayýf;
    private javax.swing.JLabel lbl_Kek;
    private javax.swing.JLabel lbl_Pasta;
    // End of variables declaration//GEN-END:variables

}
