
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author melik
 */
public class TarifVeAlýþveriþ_3 extends javax.swing.JFrame {

    //DEÐÝÞKENLERÝM
    public static int bakiyem3 = 100;                                           
    public int tutar3;  
    public static int kalanBakiye3 = 100;
    public int TelKadayýfDeðeri3;                                 
    public int TozÞekerDeðeri3;
    public int TereyaðýDeðeri3;
    public int CevizDeðeri3;
    public int SuDeðeri3;
    public int LimonSuyuDeðeri3;
    
    /**
     * Creates new form TarifVeAlýþveriþ_3
     */
    public TarifVeAlýþveriþ_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKadayýf_GeriTuþu = new javax.swing.JButton();
        lblKadayýf_Baþlik = new javax.swing.JLabel();
        lblKadayýf_Malzemeler = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKadayýf_MalzemeBilgisi = new javax.swing.JTextArea();
        lblKadayýf_TarifBaþlýk = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKadayýf_TarifBilgisi = new javax.swing.JTextArea();
        lblKadayýf_Alýþveriþ = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnKadayýf_TelKadayýf = new javax.swing.JSpinner();
        spnKadayýf_TozÞeker = new javax.swing.JSpinner();
        spnKadayýf_Tereyaðý = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnKadayýf_Ceviz = new javax.swing.JSpinner();
        spnKadayýf_Su = new javax.swing.JSpinner();
        spnKadayýf_LimonSuyu = new javax.swing.JSpinner();
        lblKadayýf_Bakiye = new javax.swing.JLabel();
        btnKadayýf_Hesapla = new javax.swing.JButton();
        lblKadayýf_Tutar = new javax.swing.JLabel();
        lblKadayýf_KalanBakiye = new javax.swing.JLabel();
        btnKadayýf_SipariþEt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKadayýf_GeriTuþu.setBackground(new java.awt.Color(153, 153, 153));
        btnKadayýf_GeriTuþu.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnKadayýf_GeriTuþu.setText("Geri");
        btnKadayýf_GeriTuþu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKadayýf_GeriTuþuActionPerformed(evt);
            }
        });

        lblKadayýf_Baþlik.setBackground(new java.awt.Color(0, 0, 0));
        lblKadayýf_Baþlik.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKadayýf_Baþlik.setForeground(new java.awt.Color(255, 0, 51));
        lblKadayýf_Baþlik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKadayýf_Baþlik.setText("Kadayýf Tarifi");
        lblKadayýf_Baþlik.setToolTipText("");
        lblKadayýf_Baþlik.setOpaque(true);

        lblKadayýf_Malzemeler.setBackground(new java.awt.Color(204, 204, 255));
        lblKadayýf_Malzemeler.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKadayýf_Malzemeler.setForeground(new java.awt.Color(255, 0, 102));
        lblKadayýf_Malzemeler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKadayýf_Malzemeler.setText("Malzemeler");
        lblKadayýf_Malzemeler.setOpaque(true);

        txtKadayýf_MalzemeBilgisi.setEditable(false);
        txtKadayýf_MalzemeBilgisi.setBackground(new java.awt.Color(204, 204, 255));
        txtKadayýf_MalzemeBilgisi.setColumns(20);
        txtKadayýf_MalzemeBilgisi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtKadayýf_MalzemeBilgisi.setLineWrap(true);
        txtKadayýf_MalzemeBilgisi.setRows(5);
        txtKadayýf_MalzemeBilgisi.setText("- Tel kadayýf  500 Gr                (KG 15 TL)\n- Tereyaðý 200 Gr                     (KG 25)\n- 1 kase ceviz 150 Gr                (KG 15 TL)\n\nÞerbeti için:\n- 3 bardak toz þeker 600 Gr      (KG 10 TL)\n- 4 bardak su 200*4                 (200 ml 3 TL)\n- Yarým limon suyu 50 Ml       (100 ml 8 TL)");
        txtKadayýf_MalzemeBilgisi.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtKadayýf_MalzemeBilgisi);

        lblKadayýf_TarifBaþlýk.setBackground(new java.awt.Color(204, 204, 255));
        lblKadayýf_TarifBaþlýk.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKadayýf_TarifBaþlýk.setForeground(new java.awt.Color(255, 0, 51));
        lblKadayýf_TarifBaþlýk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKadayýf_TarifBaþlýk.setText("Tarifi");
        lblKadayýf_TarifBaþlýk.setOpaque(true);

        txtKadayýf_TarifBilgisi.setEditable(false);
        txtKadayýf_TarifBilgisi.setBackground(new java.awt.Color(204, 204, 255));
        txtKadayýf_TarifBilgisi.setColumns(20);
        txtKadayýf_TarifBilgisi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtKadayýf_TarifBilgisi.setLineWrap(true);
        txtKadayýf_TarifBilgisi.setRows(5);
        txtKadayýf_TarifBilgisi.setText("Ýlk olarak þerbeti hazýrlamak için þeker ve suyu küçük bir tencereye aktaralým.Kaynamaya baþladýktan 10 dk. sonra limon suyunu ekleyelim, 5 dakika daha kaynattýktan sonra ocaktan alalým ve soðumaya býrakalým.kaba aldýðýmýz tel kadayýflarýn üzerine tereyaðý gezdirelim.Güzelce harmanlanarak kadayýf tellerinin yaðlanmasýný saðlayalým.Kadayýfýn yarýsýný alalým ve küçük boy fýrýn kabýna yerleþtirelim ve üzerine avuç içi ile bastýrarak sýkýþmasýný saðlayalým.Üzerine bol miktarda ceviz içi serpelim ve kalan kadayýfý cevizlerin üzerine yayalým. Yine avuç içi ile güzelce bastýralým.Tatlýmýzý 180°C önceden ýsýtýlmýþ fýrýnda 40 dakika kadar güzelce kýzartalým.Daha sonra soðutulmuþ þerbetimizi tatlýmýzýn üzerine yayalým.Ardýndan þerbetini çekmesi için bir kaç saat dinlendirelim.Þerbetini çeken tatlýmýzý Uygun bir servis tabaðýna alarak servis edelim. Afiyet olsun.");
        txtKadayýf_TarifBilgisi.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtKadayýf_TarifBilgisi);

        lblKadayýf_Alýþveriþ.setBackground(new java.awt.Color(204, 204, 255));
        lblKadayýf_Alýþveriþ.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKadayýf_Alýþveriþ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKadayýf_Alýþveriþ.setText("Alýþveriþ");
        lblKadayýf_Alýþveriþ.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/tel-kadayif.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kadayýf (500 g)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/tozÞeker - Kopya.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Toz Þeker (Kg)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(225, 225, 225));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/tereyaðý.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tereyaðý (Kg)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        spnKadayýf_TelKadayýf.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKadayýf_TelKadayýf.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKadayýf_TelKadayýfAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnKadayýf_TozÞeker.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKadayýf_TozÞeker.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKadayýf_TozÞekerAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnKadayýf_Tereyaðý.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKadayýf_Tereyaðý.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKadayýf_TereyaðýAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/ceviz.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ceviz (Kg)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/SUUU.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Su (200 ml)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/limon_suyu.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Limon suyu (100 ml)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        spnKadayýf_Ceviz.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKadayýf_Ceviz.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKadayýf_CevizAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnKadayýf_Su.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKadayýf_Su.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKadayýf_SuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnKadayýf_LimonSuyu.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKadayýf_LimonSuyu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKadayýf_LimonSuyuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblKadayýf_Bakiye.setBackground(new java.awt.Color(204, 204, 255));
        lblKadayýf_Bakiye.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblKadayýf_Bakiye.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKadayýf_Bakiye.setText("Bakiyem : ");
        lblKadayýf_Bakiye.setOpaque(true);
        lblKadayýf_Bakiye.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblKadayýf_BakiyeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnKadayýf_Hesapla.setBackground(new java.awt.Color(153, 153, 153));
        btnKadayýf_Hesapla.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnKadayýf_Hesapla.setText("Hesapla");
        btnKadayýf_Hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKadayýf_HesaplaActionPerformed(evt);
            }
        });

        lblKadayýf_Tutar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKadayýf_Tutar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKadayýf_Tutar.setText("Tutar : ");

        lblKadayýf_KalanBakiye.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKadayýf_KalanBakiye.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKadayýf_KalanBakiye.setText("Kalacak Bakiye : ");

        btnKadayýf_SipariþEt.setBackground(new java.awt.Color(153, 153, 153));
        btnKadayýf_SipariþEt.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnKadayýf_SipariþEt.setText("Sipariþ et!");
        btnKadayýf_SipariþEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKadayýf_SipariþEtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblKadayýf_Malzemeler, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(spnKadayýf_TelKadayýf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnKadayýf_Ceviz))
                                        .addGap(80, 80, 80)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnKadayýf_Su, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnKadayýf_TozÞeker, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(spnKadayýf_Tereyaðý, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(spnKadayýf_LimonSuyu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                                .addComponent(lblKadayýf_Tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblKadayýf_KalanBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblKadayýf_Alýþveriþ, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(335, 335, 335)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnKadayýf_Hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblKadayýf_TarifBaþlýk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKadayýf_SipariþEt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnKadayýf_GeriTuþu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKadayýf_Baþlik, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279)
                        .addComponent(lblKadayýf_Bakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKadayýf_GeriTuþu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKadayýf_Bakiye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKadayýf_Baþlik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKadayýf_Malzemeler, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKadayýf_Alýþveriþ, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnKadayýf_TelKadayýf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnKadayýf_TozÞeker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnKadayýf_Tereyaðý, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnKadayýf_Hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnKadayýf_Ceviz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnKadayýf_Su, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnKadayýf_LimonSuyu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKadayýf_Tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKadayýf_KalanBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnKadayýf_SipariþEt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKadayýf_TarifBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKadayýf_GeriTuþuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKadayýf_GeriTuþuActionPerformed
        ArkaBölüm arka4 = new ArkaBölüm();
        arka4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKadayýf_GeriTuþuActionPerformed

    private void btnKadayýf_HesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKadayýf_HesaplaActionPerformed
        
        tutar3 = (TelKadayýfDeðeri3 * 15)+(TozÞekerDeðeri3 * 10)+(TereyaðýDeðeri3 * 25)+(CevizDeðeri3 * 15)+(SuDeðeri3 * 3)+(LimonSuyuDeðeri3 * 8); //ALDIKLARININ DEGERINI BURAYA YAZACAKSIN
        kalanBakiye3 = bakiyem3 - tutar3;
          
        lblKadayýf_KalanBakiye.setText("Kalacak Bakiye : " + String.valueOf(kalanBakiye3));
        lblKadayýf_Tutar.setText("Tutar : " + tutar3);
    }//GEN-LAST:event_btnKadayýf_HesaplaActionPerformed

    private void lblKadayýf_BakiyeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblKadayýf_BakiyeAncestorAdded
        TarifVeAlýþveriþ t1Pasta = new TarifVeAlýþveriþ();
        TarifVeAlýþveriþ_2 t2kek = new TarifVeAlýþveriþ_2();
        
        if(t1Pasta.bakiyem != 100 || t2kek.bakiyem2 != 100){
            if(t1Pasta.bakiyem <= t2kek.bakiyem2){
                bakiyem3 = t1Pasta.bakiyem;
            }
            else if(t1Pasta.bakiyem > t2kek.bakiyem2){
                bakiyem3 = t2kek.bakiyem2;
            }
        }
        lblKadayýf_Bakiye.setText("BAKÝYEM : " + bakiyem3);
    }//GEN-LAST:event_lblKadayýf_BakiyeAncestorAdded

    private void btnKadayýf_SipariþEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKadayýf_SipariþEtActionPerformed
        if(tutar3 == 0){
            JOptionPane.showMessageDialog(rootPane, "LÜTFEN SEPETÝNÝZE ÜRÜN EKLEYÝNÝZ.");
        }
        else {
            if(tutar3 > bakiyem3){
              lblKadayýf_KalanBakiye.setText("Kalacak Bakiye : " + String.valueOf(kalanBakiye3));
              JOptionPane.showMessageDialog(rootPane, "BAKÝYE YETERSÝZ!");
          }
          else {
              lblKadayýf_KalanBakiye.setText("Kalacak Bakiye : " + String.valueOf(kalanBakiye3));
              bakiyem3 = kalanBakiye3;
              lblKadayýf_Tutar.setText("Tutar : " + String.valueOf(0));
              lblKadayýf_Bakiye.setText("BAKÝYEM : " + (bakiyem3));
              JOptionPane.showMessageDialog(rootPane, "SÝPARÝÞÝNÝZ ALINMIÞTIR.");
          }
        }
    }//GEN-LAST:event_btnKadayýf_SipariþEtActionPerformed

    private void spnKadayýf_TelKadayýfAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKadayýf_TelKadayýfAncestorAdded
       spnKadayýf_TelKadayýf.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                TelKadayýfDeðeri3 = (int) spnKadayýf_TelKadayýf.getValue();
            }
        });
    }//GEN-LAST:event_spnKadayýf_TelKadayýfAncestorAdded

    private void spnKadayýf_TozÞekerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKadayýf_TozÞekerAncestorAdded
        spnKadayýf_TozÞeker.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                TozÞekerDeðeri3 = (int) spnKadayýf_TozÞeker.getValue();
            }
        });
    }//GEN-LAST:event_spnKadayýf_TozÞekerAncestorAdded

    private void spnKadayýf_TereyaðýAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKadayýf_TereyaðýAncestorAdded
        spnKadayýf_Tereyaðý.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                TereyaðýDeðeri3 = (int) spnKadayýf_Tereyaðý.getValue();
            }
        });
    }//GEN-LAST:event_spnKadayýf_TereyaðýAncestorAdded

    private void spnKadayýf_CevizAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKadayýf_CevizAncestorAdded
        spnKadayýf_Ceviz.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                CevizDeðeri3 = (int) spnKadayýf_Ceviz.getValue();
            }
        });
    }//GEN-LAST:event_spnKadayýf_CevizAncestorAdded

    private void spnKadayýf_SuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKadayýf_SuAncestorAdded
        spnKadayýf_Su.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
               SuDeðeri3 = (int) spnKadayýf_Su.getValue();
            }
        });
    }//GEN-LAST:event_spnKadayýf_SuAncestorAdded

    private void spnKadayýf_LimonSuyuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKadayýf_LimonSuyuAncestorAdded
       spnKadayýf_LimonSuyu.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
              LimonSuyuDeðeri3 = (int) spnKadayýf_LimonSuyu.getValue();
            }
        });
    }//GEN-LAST:event_spnKadayýf_LimonSuyuAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarifVeAlýþveriþ_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKadayýf_GeriTuþu;
    private javax.swing.JButton btnKadayýf_Hesapla;
    private javax.swing.JButton btnKadayýf_SipariþEt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKadayýf_Alýþveriþ;
    private javax.swing.JLabel lblKadayýf_Bakiye;
    private javax.swing.JLabel lblKadayýf_Baþlik;
    private javax.swing.JLabel lblKadayýf_KalanBakiye;
    private javax.swing.JLabel lblKadayýf_Malzemeler;
    private javax.swing.JLabel lblKadayýf_TarifBaþlýk;
    private javax.swing.JLabel lblKadayýf_Tutar;
    private javax.swing.JSpinner spnKadayýf_Ceviz;
    private javax.swing.JSpinner spnKadayýf_LimonSuyu;
    private javax.swing.JSpinner spnKadayýf_Su;
    private javax.swing.JSpinner spnKadayýf_TelKadayýf;
    private javax.swing.JSpinner spnKadayýf_Tereyaðý;
    private javax.swing.JSpinner spnKadayýf_TozÞeker;
    private javax.swing.JTextArea txtKadayýf_MalzemeBilgisi;
    private javax.swing.JTextArea txtKadayýf_TarifBilgisi;
    // End of variables declaration//GEN-END:variables
}
