
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author melik
 */
public class TarifVeAlýþveriþ_2 extends javax.swing.JFrame {
    
    //DEÐÝÞKENLERÝM
    public static int bakiyem2 = 100;                                           
    public int tutar2;
    public static int kalanBakiye2 = 100;
    public int yumurtaDeðeri2;                                     
    public int tozÞekerDeðeri2;
    public int kabartmaTozuDeðeri2;
    public int yaðDeðeri2;
    public int unDeðeri2;
    public int sütDeðeri2;
    public int vanilyaDeðeri2;
    public int kakaoDeðeri2;
   
    
    
    
    
    
    
    /**
     * Creates new form TarifVeAlýþveriþ_2
     */
    public TarifVeAlýþveriþ_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKek_GeriTuþu = new javax.swing.JButton();
        lblKek_Baþlýk = new javax.swing.JLabel();
        lblKek_MalzemelerBaþlýk = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKek_MalzemeBilgisi = new javax.swing.JTextArea();
        txtKek_TarifBaþlýk = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKek_TarifBilgisi = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblKek_Bakiye = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnKek_Yumurta = new javax.swing.JSpinner();
        spnKek_TozÞeker = new javax.swing.JSpinner();
        spnKek_Süt = new javax.swing.JSpinner();
        spnKek_Un = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spnKek_SývýYað = new javax.swing.JSpinner();
        spnKek_KabartmaTozu = new javax.swing.JSpinner();
        spnKek_Vanilya = new javax.swing.JSpinner();
        spnKek_Kakao = new javax.swing.JSpinner();
        btnKek_Hesapla = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblKek_Tutar = new javax.swing.JLabel();
        lblKek_KalanBakiye = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKek_GeriTuþu.setBackground(new java.awt.Color(153, 153, 153));
        btnKek_GeriTuþu.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnKek_GeriTuþu.setText("Geri");
        btnKek_GeriTuþu.setOpaque(true);
        btnKek_GeriTuþu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKek_GeriTuþuActionPerformed(evt);
            }
        });

        lblKek_Baþlýk.setBackground(new java.awt.Color(0, 0, 0));
        lblKek_Baþlýk.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKek_Baþlýk.setForeground(new java.awt.Color(255, 0, 51));
        lblKek_Baþlýk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKek_Baþlýk.setText("Kek Tarifi");
        lblKek_Baþlýk.setOpaque(true);

        lblKek_MalzemelerBaþlýk.setBackground(new java.awt.Color(204, 204, 255));
        lblKek_MalzemelerBaþlýk.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKek_MalzemelerBaþlýk.setForeground(new java.awt.Color(255, 0, 51));
        lblKek_MalzemelerBaþlýk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKek_MalzemelerBaþlýk.setText("Malzemeler");
        lblKek_MalzemelerBaþlýk.setOpaque(true);

        txtKek_MalzemeBilgisi.setEditable(false);
        txtKek_MalzemeBilgisi.setBackground(new java.awt.Color(204, 204, 255));
        txtKek_MalzemeBilgisi.setColumns(20);
        txtKek_MalzemeBilgisi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtKek_MalzemeBilgisi.setLineWrap(true);
        txtKek_MalzemeBilgisi.setRows(5);
        txtKek_MalzemeBilgisi.setText("- 5 adet yumurta                           (Adet 3 TL) \n- 2 su bardaðý þeker 400 ml          (KG 10 TL)\n- 2 su bardaðý süt  400 ml             (L 7 TL)\n- 1 su bardaðý un  200 Gr              (KG 8 TL)\n- 1/5 su bardaðý sývý yað  40 ml    (L 10 TL)\n- 1 paket kabartma tozu               (5'LÝ 5 TL)\n- 1 paket vanilya                           (PAKET 5 TL)\n- 5 yemek kaþýðý kakao 100 Gr     (100 GR 10 TL)");
        txtKek_MalzemeBilgisi.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtKek_MalzemeBilgisi);

        txtKek_TarifBaþlýk.setBackground(new java.awt.Color(204, 204, 255));
        txtKek_TarifBaþlýk.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtKek_TarifBaþlýk.setForeground(new java.awt.Color(255, 0, 51));
        txtKek_TarifBaþlýk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtKek_TarifBaþlýk.setText("Tarifi");
        txtKek_TarifBaþlýk.setOpaque(true);

        txtKek_TarifBilgisi.setEditable(false);
        txtKek_TarifBilgisi.setBackground(new java.awt.Color(204, 204, 255));
        txtKek_TarifBilgisi.setColumns(20);
        txtKek_TarifBilgisi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtKek_TarifBilgisi.setLineWrap(true);
        txtKek_TarifBilgisi.setRows(5);
        txtKek_TarifBilgisi.setText("Öncelikle yumurta ve þekeri uygun bir kaba alarak mikser yardýmý ile beyazlaþýp köpük köpük olana kadar 5 dakika boyunca çýrpalým.Ardýndan sývý yað, süt, un, kakao, kabartma tozu ve vanilyayý ekleyerek çýrpmaya devam edelim.Homojen bir kývam aldýktan sonra borcamý sývý yað ile yaðlayalým.Sosu için tüm malzemeleri tencereye koyalým ve güzelce çýrpalým(1 su bardaðý þeker,1 su bardaðý süt (200 ml),1/2 (yarým) su bardaðý sývý yað (100 ml),2 yemek kaþýðý kakao).Sosumuzu kaynayana kadar sürekli karýþtýrarak piþirelim.Sos piþtikten sonra kekimizin üzerine dökelim.Kekimizi dilediðimiz þekilde süsleyerek servis edelim. Afiyet olsun!");
        txtKek_TarifBilgisi.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtKek_TarifBilgisi);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alýþveriþ");
        jLabel1.setOpaque(true);

        lblKek_Bakiye.setBackground(new java.awt.Color(204, 204, 255));
        lblKek_Bakiye.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKek_Bakiye.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKek_Bakiye.setText("Bakiyem : ");
        lblKek_Bakiye.setOpaque(true);
        lblKek_Bakiye.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblKek_BakiyeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/yumurta2.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Yumurta (Adet)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/tozÞeker.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Toz Þeker (Kg)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/kabartmaTozu.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kabartma tozu (Paket)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/yað.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Yað (L)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        spnKek_Yumurta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKek_Yumurta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKek_YumurtaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnKek_TozÞeker.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKek_TozÞeker.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKek_TozÞekerAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnKek_Süt.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKek_Süt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKek_SütAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnKek_Un.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKek_Un.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKek_UnAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/un.jpg"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Un (Kg)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/süt.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Süt (L)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(255, 255, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/kakao.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kakao (100 g)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/vanilya.jpg"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Vanilya (Paket)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        spnKek_SývýYað.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKek_SývýYað.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKek_SývýYaðAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnKek_KabartmaTozu.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKek_KabartmaTozu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKek_KabartmaTozuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnKek_Vanilya.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKek_Vanilya.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKek_VanilyaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnKek_Kakao.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnKek_Kakao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnKek_KakaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnKek_Hesapla.setBackground(new java.awt.Color(153, 153, 153));
        btnKek_Hesapla.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnKek_Hesapla.setText("Hesapla");
        btnKek_Hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKek_HesaplaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setText("Sipariþ et!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblKek_Tutar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKek_Tutar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKek_Tutar.setText("Tutar : ");

        lblKek_KalanBakiye.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblKek_KalanBakiye.setText("Kalacak Bakiye : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtKek_TarifBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spnKek_Yumurta)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(spnKek_Un))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 17, Short.MAX_VALUE))
                                        .addComponent(spnKek_TozÞeker)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(spnKek_Süt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spnKek_KabartmaTozu, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(spnKek_Kakao, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spnKek_SývýYað, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(spnKek_Vanilya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblKek_MalzemelerBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnKek_GeriTuþu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKek_Baþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblKek_Bakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnKek_Hesapla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblKek_KalanBakiye, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(lblKek_Tutar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKek_GeriTuþu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKek_Baþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKek_Bakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKek_MalzemelerBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnKek_Yumurta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spnKek_TozÞeker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnKek_KabartmaTozu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnKek_SývýYað, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtKek_TarifBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnKek_Kakao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnKek_Süt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnKek_Un, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnKek_Vanilya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKek_Hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKek_Tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKek_KalanBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKek_GeriTuþuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKek_GeriTuþuActionPerformed
        ArkaBölüm arka3 = new ArkaBölüm();
        arka3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKek_GeriTuþuActionPerformed

    private void btnKek_HesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKek_HesaplaActionPerformed
          //SONUÇ BURADA YAZILACAK
          tutar2 = (yumurtaDeðeri2 * 3)+(tozÞekerDeðeri2 * 10)+(kabartmaTozuDeðeri2 * 5)+(yaðDeðeri2 * 10)+(unDeðeri2 * 8)+(sütDeðeri2 * 7)+(vanilyaDeðeri2 * 5)+(kakaoDeðeri2 * 10); //ALDIKLARININ DEGERINI BURAYA YAZACAKSIN
          kalanBakiye2 = bakiyem2 - tutar2;
          
          lblKek_KalanBakiye.setText("Kalacak Bakiye : " + String.valueOf(kalanBakiye2));
          lblKek_Tutar.setText("Tutar : " + tutar2);
    }//GEN-LAST:event_btnKek_HesaplaActionPerformed

    private void lblKek_BakiyeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblKek_BakiyeAncestorAdded
        TarifVeAlýþveriþ t1Pasta = new TarifVeAlýþveriþ();
        TarifVeAlýþveriþ_3 t3Kadayýf = new TarifVeAlýþveriþ_3();
        
        if(t1Pasta.bakiyem != 100 || t3Kadayýf.bakiyem3 != 100){
            if(t1Pasta.bakiyem <= t3Kadayýf.bakiyem3){
                bakiyem2 = t1Pasta.bakiyem;
            }
            else if(t1Pasta.bakiyem > t3Kadayýf.bakiyem3){
                bakiyem2 = t3Kadayýf.bakiyem3;
            }
        }
        lblKek_Bakiye.setText("BAKÝYEM : " + bakiyem2);
    }//GEN-LAST:event_lblKek_BakiyeAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(tutar2 == 0){
            JOptionPane.showMessageDialog(rootPane, "LÜTFEN SEPETÝNÝZE ÜRÜN EKLEYÝNÝZ.");
        }
        else {
            if(tutar2 > bakiyem2){
              lblKek_KalanBakiye.setText("Kalacak Bakiye : " + String.valueOf(kalanBakiye2));
              JOptionPane.showMessageDialog(rootPane, "BAKÝYE YETERSÝZ!");
          }
          else {
              lblKek_KalanBakiye.setText("Kalacak Bakiye : " + String.valueOf(kalanBakiye2));
              bakiyem2 = kalanBakiye2;
              lblKek_Tutar.setText("Tutar : " + String.valueOf(0));
              lblKek_Bakiye.setText("BAKÝYEM : " + (bakiyem2));
              JOptionPane.showMessageDialog(rootPane, "SÝPARÝÞÝNÝZ ALINMIÞTIR.");
          }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void spnKek_YumurtaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKek_YumurtaAncestorAdded
        spnKek_Yumurta.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                yumurtaDeðeri2 = (int) spnKek_Yumurta.getValue();
            }
        });
    }//GEN-LAST:event_spnKek_YumurtaAncestorAdded

    private void spnKek_TozÞekerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKek_TozÞekerAncestorAdded
        spnKek_TozÞeker.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                tozÞekerDeðeri2 = (int) spnKek_TozÞeker.getValue();
            }
        });
    }//GEN-LAST:event_spnKek_TozÞekerAncestorAdded

    private void spnKek_KabartmaTozuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKek_KabartmaTozuAncestorAdded
        spnKek_KabartmaTozu.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                kabartmaTozuDeðeri2 = (int) spnKek_KabartmaTozu.getValue();
            }
        });
    }//GEN-LAST:event_spnKek_KabartmaTozuAncestorAdded

    private void spnKek_SývýYaðAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKek_SývýYaðAncestorAdded
        spnKek_SývýYað.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                yaðDeðeri2 = (int) spnKek_SývýYað.getValue();
            }
        });
    }//GEN-LAST:event_spnKek_SývýYaðAncestorAdded

    private void spnKek_UnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKek_UnAncestorAdded
        spnKek_Un.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                unDeðeri2 = (int) spnKek_Un.getValue();
            }
        });
    }//GEN-LAST:event_spnKek_UnAncestorAdded

    private void spnKek_SütAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKek_SütAncestorAdded
        spnKek_Süt.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                sütDeðeri2 = (int) spnKek_Süt.getValue();
            }
        });
    }//GEN-LAST:event_spnKek_SütAncestorAdded

    private void spnKek_KakaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKek_KakaoAncestorAdded
        spnKek_Kakao.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                kakaoDeðeri2 = (int) spnKek_Kakao.getValue();
            }
        });
    }//GEN-LAST:event_spnKek_KakaoAncestorAdded

    private void spnKek_VanilyaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnKek_VanilyaAncestorAdded
        spnKek_Vanilya.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                vanilyaDeðeri2 = (int) spnKek_Vanilya.getValue();
            }
        });
    }//GEN-LAST:event_spnKek_VanilyaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarifVeAlýþveriþ_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKek_GeriTuþu;
    private javax.swing.JButton btnKek_Hesapla;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKek_Bakiye;
    private javax.swing.JLabel lblKek_Baþlýk;
    private javax.swing.JLabel lblKek_KalanBakiye;
    private javax.swing.JLabel lblKek_MalzemelerBaþlýk;
    private javax.swing.JLabel lblKek_Tutar;
    private javax.swing.JSpinner spnKek_KabartmaTozu;
    private javax.swing.JSpinner spnKek_Kakao;
    private javax.swing.JSpinner spnKek_Süt;
    private javax.swing.JSpinner spnKek_SývýYað;
    private javax.swing.JSpinner spnKek_TozÞeker;
    private javax.swing.JSpinner spnKek_Un;
    private javax.swing.JSpinner spnKek_Vanilya;
    private javax.swing.JSpinner spnKek_Yumurta;
    private javax.swing.JTextArea txtKek_MalzemeBilgisi;
    private javax.swing.JLabel txtKek_TarifBaþlýk;
    private javax.swing.JTextArea txtKek_TarifBilgisi;
    // End of variables declaration//GEN-END:variables
}
