
import com.sun.source.tree.Tree;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author melik
 */
public class TarifVeAlýþveriþ extends javax.swing.JFrame {

    //DEÐÝÞKENLERÝM PANEL1
    public static int bakiyem = 100;                                           
    public int tutar;
    public static int kalanBakiye = 100;
    public int yumurtaDeðeri;                                     
    public int tozÞekerDeðeri;
    public int kabartmaTozuDeðeri;
    public int yaðDeðeri;
    public int unDeðeri;
    public int sütDeðeri;
    public int kremÞantiDeðeri;
    public int karýþýkMeyveDeðer;
   
    /**
     * Creates new form TarifVeAlýþveriþ
     */
    public TarifVeAlýþveriþ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPasta_Tarif = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnPasta_GeriTuþu = new javax.swing.JButton();
        lblPasta_Bakiye = new javax.swing.JLabel();
        lblPasta_Baþlýk = new javax.swing.JLabel();
        lblPasta_AlýþverisBaþlýk = new javax.swing.JLabel();
        btnPasta_Hesapla = new javax.swing.JButton();
        lblPasta_Tutar = new javax.swing.JLabel();
        lblPasta_KalanBakiye = new javax.swing.JLabel();
        lblPasta_MalzemelerBaþlýk = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPasta_MalzemeBilgisi = new javax.swing.JTextArea();
        lblPasta_TarifBaþlýk = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPasta_Yapýlýþ = new javax.swing.JTextArea();
        spnPasta_TozÞeker = new javax.swing.JSpinner();
        spnPasta_Yumurta = new javax.swing.JSpinner();
        spnPasta_KabartmaTozu = new javax.swing.JSpinner();
        spnPasta_Yað = new javax.swing.JSpinner();
        spnPasta_Un = new javax.swing.JSpinner();
        spnPasta_Süt = new javax.swing.JSpinner();
        spnPasta_KremÞanti = new javax.swing.JSpinner();
        lblPasta_ResimlerTozÞeker = new javax.swing.JLabel();
        lblPasta_ResimlerKabartmaTozu = new javax.swing.JLabel();
        lblPasta_ResimlerUn = new javax.swing.JLabel();
        lblPasta_ResimlerSüt = new javax.swing.JLabel();
        lblPasta_ResimlerKremÞanti = new javax.swing.JLabel();
        lblPasta_ResimlerYumurta = new javax.swing.JLabel();
        lblPasta_ResimlerYað = new javax.swing.JLabel();
        lblPasta_ResimlerMeyve = new javax.swing.JLabel();
        spnPasta_KarýþýkMeyve = new javax.swing.JSpinner();
        btnPasta_SipariþEt = new javax.swing.JButton();

        txtPasta_Tarif.setColumns(20);
        txtPasta_Tarif.setLineWrap(true);
        txtPasta_Tarif.setRows(5);
        txtPasta_Tarif.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtPasta_Tarif);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 818));

        btnPasta_GeriTuþu.setBackground(new java.awt.Color(153, 153, 153));
        btnPasta_GeriTuþu.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnPasta_GeriTuþu.setText("Geri");
        btnPasta_GeriTuþu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasta_GeriTuþuActionPerformed(evt);
            }
        });

        lblPasta_Bakiye.setBackground(new java.awt.Color(204, 204, 255));
        lblPasta_Bakiye.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblPasta_Bakiye.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPasta_Bakiye.setText("Bakiyem :");
        lblPasta_Bakiye.setOpaque(true);
        lblPasta_Bakiye.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblPasta_BakiyeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblPasta_Baþlýk.setBackground(new java.awt.Color(0, 0, 0));
        lblPasta_Baþlýk.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblPasta_Baþlýk.setForeground(new java.awt.Color(255, 0, 0));
        lblPasta_Baþlýk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasta_Baþlýk.setText("Pasta Tarifi");
        lblPasta_Baþlýk.setOpaque(true);

        lblPasta_AlýþverisBaþlýk.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPasta_AlýþverisBaþlýk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasta_AlýþverisBaþlýk.setText("Alýþveriþ");

        btnPasta_Hesapla.setBackground(new java.awt.Color(153, 153, 153));
        btnPasta_Hesapla.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnPasta_Hesapla.setText("Hesapla");
        btnPasta_Hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasta_HesaplaActionPerformed(evt);
            }
        });

        lblPasta_Tutar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblPasta_Tutar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPasta_Tutar.setText("Tutar :");

        lblPasta_KalanBakiye.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblPasta_KalanBakiye.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPasta_KalanBakiye.setText("Kalacak bakiye :");

        lblPasta_MalzemelerBaþlýk.setBackground(new java.awt.Color(204, 204, 255));
        lblPasta_MalzemelerBaþlýk.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblPasta_MalzemelerBaþlýk.setForeground(new java.awt.Color(255, 0, 51));
        lblPasta_MalzemelerBaþlýk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasta_MalzemelerBaþlýk.setText("Malzemeler");
        lblPasta_MalzemelerBaþlýk.setOpaque(true);

        txtPasta_MalzemeBilgisi.setEditable(false);
        txtPasta_MalzemeBilgisi.setBackground(new java.awt.Color(204, 204, 255));
        txtPasta_MalzemeBilgisi.setColumns(20);
        txtPasta_MalzemeBilgisi.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtPasta_MalzemeBilgisi.setLineWrap(true);
        txtPasta_MalzemeBilgisi.setRows(5);
        txtPasta_MalzemeBilgisi.setText("- 4 adet yumurta                            (Adet 3 TL)\n- 1 su bardaðý toz þeker 200 Gr      (KG 10 TL)\n- 1 paket kabartma tozu                 (5'LÝ 5 TL)\n- 3 yemek kaþýðý yað 20 ml            ( L 10 TL)\n- 1,5 su bardaðý un  300 Gr            ( KG 8 TL )\n- 1 su bardaðý süt 200 ml               ( L 7 TL)\n- 1 paket toz krem þanti                 (Adet 10 TL)\n- Ýstediðin türde meyve                  (KG 30 TL)");
        txtPasta_MalzemeBilgisi.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtPasta_MalzemeBilgisi);

        lblPasta_TarifBaþlýk.setBackground(new java.awt.Color(204, 204, 255));
        lblPasta_TarifBaþlýk.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblPasta_TarifBaþlýk.setForeground(new java.awt.Color(255, 51, 51));
        lblPasta_TarifBaþlýk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasta_TarifBaþlýk.setText("Tarifi");
        lblPasta_TarifBaþlýk.setOpaque(true);

        txtPasta_Yapýlýþ.setEditable(false);
        txtPasta_Yapýlýþ.setBackground(new java.awt.Color(204, 204, 255));
        txtPasta_Yapýlýþ.setColumns(20);
        txtPasta_Yapýlýþ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPasta_Yapýlýþ.setLineWrap(true);
        txtPasta_Yapýlýþ.setRows(5);
        txtPasta_Yapýlýþ.setText("Yumurtalarý bir kabýn içerisine kýrýn ve üzerine toz þeker ilave edip güzelce çýrpýn.Köpük köpük olan karýþýmýn üzerine,kabartma tozu ve unu eleyerek ekleyin.Spatula yardýmýyla güzelce karýþtýrýn.Yaðlanmýþ kek kalýbýna harcý aktarýn. 180 derecede önceden ýsýtýlmýþ fýrýnda 25 dakika piþirin. Çýkarýp oda sýcaklýðýnda soðumaya býrakýn.Derin bir kaseye soðuk süt ve toz krem þantiyi koyun ve köpük köpük olana ve kývam alana kadar mikser ile 5 dakika çýrpýn.Ardýndan üzerine hazýrlamýþ olduðunuz krem þantiyi ekleyin ve  güzelce yayýn.Üzerine meyveleri dilediðiniz gibi yerleþtirin.Buzdolabýnda birkaç saat dinlendirin.Afiyetler olsun!\n");
        txtPasta_Yapýlýþ.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtPasta_Yapýlýþ);

        spnPasta_TozÞeker.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnPasta_TozÞeker.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnPasta_TozÞekerAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnPasta_Yumurta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnPasta_Yumurta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnPasta_YumurtaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnPasta_KabartmaTozu.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnPasta_KabartmaTozu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnPasta_KabartmaTozuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnPasta_Yað.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnPasta_Yað.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnPasta_YaðAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnPasta_Un.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnPasta_Un.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnPasta_UnAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnPasta_Süt.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnPasta_Süt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnPasta_SütAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        spnPasta_KremÞanti.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnPasta_KremÞanti.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnPasta_KremÞantiAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblPasta_ResimlerTozÞeker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/tozÞeker.jpg"))); // NOI18N
        lblPasta_ResimlerTozÞeker.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Toz Þeker (Kg)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        lblPasta_ResimlerKabartmaTozu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/kabartmaTozu.png"))); // NOI18N
        lblPasta_ResimlerKabartmaTozu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kabartma tozu (Paket)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        lblPasta_ResimlerUn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/un.jpg"))); // NOI18N
        lblPasta_ResimlerUn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Un (Kg)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        lblPasta_ResimlerSüt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/süt.jpg"))); // NOI18N
        lblPasta_ResimlerSüt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Süt (1 L)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N
        lblPasta_ResimlerSüt.setOpaque(true);

        lblPasta_ResimlerKremÞanti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/kremÞanti.jpg"))); // NOI18N
        lblPasta_ResimlerKremÞanti.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Krem Þanti (1 Adet)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        lblPasta_ResimlerYumurta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/yumurta2.jpg"))); // NOI18N
        lblPasta_ResimlerYumurta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Yumurta (adet)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        lblPasta_ResimlerYað.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/yað.jpg"))); // NOI18N
        lblPasta_ResimlerYað.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Yað (1 L)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        lblPasta_ResimlerMeyve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/karýþýkMeyve.jpg"))); // NOI18N
        lblPasta_ResimlerMeyve.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Karýþýk meyve (Kg)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        spnPasta_KarýþýkMeyve.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnPasta_KarýþýkMeyve.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spnPasta_KarýþýkMeyveAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnPasta_SipariþEt.setBackground(new java.awt.Color(153, 153, 153));
        btnPasta_SipariþEt.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnPasta_SipariþEt.setText("Sipariþ et!");
        btnPasta_SipariþEt.setOpaque(true);
        btnPasta_SipariþEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasta_SipariþEtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPasta_MalzemelerBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPasta_TarifBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasta_ResimlerUn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spnPasta_Yumurta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPasta_ResimlerYumurta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(spnPasta_Un, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPasta_Tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPasta_ResimlerTozÞeker, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnPasta_TozÞeker, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(spnPasta_Süt, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblPasta_ResimlerSüt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(spnPasta_KremÞanti, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblPasta_ResimlerKremÞanti, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(spnPasta_KabartmaTozu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblPasta_ResimlerKabartmaTozu, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPasta_ResimlerMeyve, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnPasta_Yað, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPasta_ResimlerYað, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnPasta_KarýþýkMeyve, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(lblPasta_AlýþverisBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(177, 177, 177))
                            .addComponent(lblPasta_KalanBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPasta_SipariþEt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPasta_Hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPasta_GeriTuþu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(474, 474, 474)
                        .addComponent(lblPasta_Baþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(306, 306, 306)
                        .addComponent(lblPasta_Bakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 1816, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnPasta_GeriTuþu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasta_MalzemelerBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPasta_Baþlýk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPasta_Bakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(lblPasta_AlýþverisBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPasta_ResimlerYumurta, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasta_ResimlerTozÞeker, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasta_ResimlerKabartmaTozu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasta_ResimlerYað, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnPasta_Yað, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnPasta_Yumurta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnPasta_TozÞeker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnPasta_KabartmaTozu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPasta_ResimlerSüt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPasta_ResimlerKremÞanti, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnPasta_Un, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(spnPasta_Süt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnPasta_KremÞanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnPasta_KarýþýkMeyve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblPasta_ResimlerMeyve, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(btnPasta_Hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPasta_Tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPasta_KalanBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPasta_SipariþEt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasta_ResimlerUn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPasta_TarifBaþlýk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(190, 190, 190))))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnPasta_GeriTuþuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasta_GeriTuþuActionPerformed
        //BU TUÞA BASILDIÐINDA ÖNCEKÝ BÖLÜME GÝDECEK
        ArkaBölüm arka2 = new ArkaBölüm();
        arka2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPasta_GeriTuþuActionPerformed
   
    private void btnPasta_HesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasta_HesaplaActionPerformed
          //SONUÇ BURADA YAZILACAK
          tutar = (yumurtaDeðeri * 3)+(tozÞekerDeðeri * 10)+(kabartmaTozuDeðeri * 5)+(yaðDeðeri * 10)+(unDeðeri * 8)+(sütDeðeri * 7)+(kremÞantiDeðeri * 10)+(karýþýkMeyveDeðer * 30); 
          kalanBakiye = bakiyem - tutar;
          
          lblPasta_Tutar.setText("Tutar : " + tutar);
          lblPasta_KalanBakiye.setText("Kalacak Bakiye : " + String.valueOf(kalanBakiye));
          
          
    }//GEN-LAST:event_btnPasta_HesaplaActionPerformed
           //PANEL 1 METOTLAR BAÞLANGIÇ
    private void spnPasta_YumurtaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnPasta_YumurtaAncestorAdded
        spnPasta_Yumurta.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                yumurtaDeðeri = (int) spnPasta_Yumurta.getValue();
            }
        });
    }//GEN-LAST:event_spnPasta_YumurtaAncestorAdded

    private void spnPasta_TozÞekerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnPasta_TozÞekerAncestorAdded
        spnPasta_TozÞeker.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent er) {
                tozÞekerDeðeri = (int) spnPasta_TozÞeker.getValue();
            }
        });
    }//GEN-LAST:event_spnPasta_TozÞekerAncestorAdded

    private void spnPasta_KabartmaTozuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnPasta_KabartmaTozuAncestorAdded
        spnPasta_KabartmaTozu.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                kabartmaTozuDeðeri = (int) spnPasta_KabartmaTozu.getValue();
            }
        });
    }//GEN-LAST:event_spnPasta_KabartmaTozuAncestorAdded

    private void spnPasta_YaðAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnPasta_YaðAncestorAdded
        spnPasta_Yað.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                yaðDeðeri = (int) spnPasta_Yað.getValue();
            }
        });
    }//GEN-LAST:event_spnPasta_YaðAncestorAdded

    private void spnPasta_UnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnPasta_UnAncestorAdded
        spnPasta_Un.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                unDeðeri = (int) spnPasta_Un.getValue();
            }
        });
    }//GEN-LAST:event_spnPasta_UnAncestorAdded

    private void spnPasta_SütAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnPasta_SütAncestorAdded
        spnPasta_Süt.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                sütDeðeri = (int) spnPasta_Süt.getValue();
            }
        });
    }//GEN-LAST:event_spnPasta_SütAncestorAdded

    private void spnPasta_KremÞantiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnPasta_KremÞantiAncestorAdded
        spnPasta_KremÞanti.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                kremÞantiDeðeri = (int) spnPasta_KremÞanti.getValue();
            }
        });
    }//GEN-LAST:event_spnPasta_KremÞantiAncestorAdded

    private void btnPasta_SipariþEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasta_SipariþEtActionPerformed
        if(tutar == 0){
            JOptionPane.showMessageDialog(rootPane, "LÜTFEN SEPETÝNÝZE ÜRÜN EKLEYÝNÝZ.");
        }
        else {
            if(tutar > bakiyem){
            JOptionPane.showMessageDialog(rootPane, "BAKÝYE YETERSÝZ!");
            lblPasta_KalanBakiye.setText("Kalacak Bakiye : " + String.valueOf(kalanBakiye));
          }
          else {
              lblPasta_KalanBakiye.setText("Kalacak Bakiye : " + String.valueOf(kalanBakiye));
              bakiyem = kalanBakiye;
              lblPasta_Bakiye.setText("BAKÝYEM : " + (bakiyem));
              lblPasta_Tutar.setText("Tutar : " + String.valueOf(0));
              JOptionPane.showMessageDialog(rootPane, "SÝPARÝÞÝNÝZ ALINMIÞTIR.");
          }
        }
    }//GEN-LAST:event_btnPasta_SipariþEtActionPerformed
    private void lblPasta_BakiyeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblPasta_BakiyeAncestorAdded
        TarifVeAlýþveriþ_2 t2kek = new TarifVeAlýþveriþ_2();
        TarifVeAlýþveriþ_3 t3Kadayýf = new TarifVeAlýþveriþ_3();
        
        if(t2kek.bakiyem2 != 100 || t3Kadayýf.bakiyem3 != 100){
            if(t2kek.bakiyem2 <= t3Kadayýf.bakiyem3){
                bakiyem = t2kek.bakiyem2;
            }
            else if(t2kek.bakiyem2 > t3Kadayýf.bakiyem3){
                bakiyem = t3Kadayýf.bakiyem3;
            }
        }
        lblPasta_Bakiye.setText("BAKÝYEM : " + bakiyem);
    }//GEN-LAST:event_lblPasta_BakiyeAncestorAdded

    private void spnPasta_KarýþýkMeyveAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spnPasta_KarýþýkMeyveAncestorAdded
        spnPasta_KarýþýkMeyve.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                karýþýkMeyveDeðer = (int) spnPasta_KarýþýkMeyve.getValue();
            }
        });
    }//GEN-LAST:event_spnPasta_KarýþýkMeyveAncestorAdded
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarifVeAlýþveriþ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarifVeAlýþveriþ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPasta_GeriTuþu;
    private javax.swing.JButton btnPasta_Hesapla;
    private javax.swing.JButton btnPasta_SipariþEt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblPasta_AlýþverisBaþlýk;
    private javax.swing.JLabel lblPasta_Bakiye;
    private javax.swing.JLabel lblPasta_Baþlýk;
    private javax.swing.JLabel lblPasta_KalanBakiye;
    private javax.swing.JLabel lblPasta_MalzemelerBaþlýk;
    private javax.swing.JLabel lblPasta_ResimlerKabartmaTozu;
    private javax.swing.JLabel lblPasta_ResimlerKremÞanti;
    private javax.swing.JLabel lblPasta_ResimlerMeyve;
    private javax.swing.JLabel lblPasta_ResimlerSüt;
    private javax.swing.JLabel lblPasta_ResimlerTozÞeker;
    private javax.swing.JLabel lblPasta_ResimlerUn;
    private javax.swing.JLabel lblPasta_ResimlerYað;
    private javax.swing.JLabel lblPasta_ResimlerYumurta;
    private javax.swing.JLabel lblPasta_TarifBaþlýk;
    private javax.swing.JLabel lblPasta_Tutar;
    private javax.swing.JSpinner spnPasta_KabartmaTozu;
    private javax.swing.JSpinner spnPasta_KarýþýkMeyve;
    private javax.swing.JSpinner spnPasta_KremÞanti;
    private javax.swing.JSpinner spnPasta_Süt;
    private javax.swing.JSpinner spnPasta_TozÞeker;
    private javax.swing.JSpinner spnPasta_Un;
    private javax.swing.JSpinner spnPasta_Yað;
    private javax.swing.JSpinner spnPasta_Yumurta;
    private javax.swing.JTextArea txtPasta_MalzemeBilgisi;
    private javax.swing.JTextArea txtPasta_Tarif;
    private javax.swing.JTextArea txtPasta_Yapýlýþ;
    // End of variables declaration//GEN-END:variables
}
