
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author melik
 */
public class YemekTarifi extends javax.swing.JFrame {

    /**
     * Creates new form YemekTarifi
     */
    public YemekTarifi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnaMenü_AnaPanel = new javax.swing.JPanel();
        lblAnaMenü_Hoþgeldiniz = new javax.swing.JLabel();
        txtAnaMenü_KullanýcýAdý = new javax.swing.JTextField();
        txtAnaMenü_Þifre = new javax.swing.JPasswordField();
        lblAnaMenü_Resimler = new javax.swing.JLabel();
        btnAnaMenü_GiriþYap = new javax.swing.JButton();
        lblAnaMenü_Resimler2 = new javax.swing.JLabel();
        lblAnaMenü_Resimler3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAnaMenü_Hoþgeldiniz.setBackground(new java.awt.Color(0, 0, 0));
        lblAnaMenü_Hoþgeldiniz.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblAnaMenü_Hoþgeldiniz.setForeground(new java.awt.Color(255, 0, 51));
        lblAnaMenü_Hoþgeldiniz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnaMenü_Hoþgeldiniz.setText("Yemek tarifi uygulamasýna hoþgeldiniz");
        lblAnaMenü_Hoþgeldiniz.setOpaque(true);

        txtAnaMenü_KullanýcýAdý.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAnaMenü_KullanýcýAdý.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAnaMenü_KullanýcýAdý.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kullanýcý Adý", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        txtAnaMenü_Þifre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAnaMenü_Þifre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAnaMenü_Þifre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Þifre", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblAnaMenü_Resimler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/MasterChef_2.jpg"))); // NOI18N

        btnAnaMenü_GiriþYap.setBackground(new java.awt.Color(153, 153, 153));
        btnAnaMenü_GiriþYap.setText("Giriþ yap");
        btnAnaMenü_GiriþYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnaMenü_GiriþYapActionPerformed(evt);
            }
        });

        lblAnaMenü_Resimler2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/cooking.png"))); // NOI18N

        lblAnaMenü_Resimler3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnaMenü_Resimler/chef.png"))); // NOI18N

        javax.swing.GroupLayout AnaMenü_AnaPanelLayout = new javax.swing.GroupLayout(AnaMenü_AnaPanel);
        AnaMenü_AnaPanel.setLayout(AnaMenü_AnaPanelLayout);
        AnaMenü_AnaPanelLayout.setHorizontalGroup(
            AnaMenü_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnaMenü_AnaPanelLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(lblAnaMenü_Hoþgeldiniz, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnaMenü_AnaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AnaMenü_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AnaMenü_AnaPanelLayout.createSequentialGroup()
                        .addGroup(AnaMenü_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAnaMenü_KullanýcýAdý)
                            .addComponent(txtAnaMenü_Þifre, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblAnaMenü_Resimler, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AnaMenü_AnaPanelLayout.createSequentialGroup()
                        .addComponent(lblAnaMenü_Resimler3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btnAnaMenü_GiriþYap, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAnaMenü_Resimler2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        AnaMenü_AnaPanelLayout.setVerticalGroup(
            AnaMenü_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnaMenü_AnaPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblAnaMenü_Hoþgeldiniz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(AnaMenü_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnaMenü_AnaPanelLayout.createSequentialGroup()
                        .addComponent(txtAnaMenü_KullanýcýAdý, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtAnaMenü_Þifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAnaMenü_Resimler))
                .addGroup(AnaMenü_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnaMenü_AnaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(AnaMenü_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnaMenü_Resimler2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAnaMenü_Resimler3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(AnaMenü_AnaPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnAnaMenü_GiriþYap, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnaMenü_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnaMenü_AnaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnaMenü_GiriþYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnaMenü_GiriþYapActionPerformed
        
        String kullanýcýAdý = txtAnaMenü_KullanýcýAdý.getText();
        String þifre = new String(txtAnaMenü_Þifre.getPassword());
        
        ArkaBölüm arka = new ArkaBölüm();
        
        if(kullanýcýAdý.equals("melik") && þifre.equals("34160")){
            arka.setVisible(true);
            this.setVisible(false);
        }
        else if(kullanýcýAdý.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Lütfen kullanýcý adý giriniz.");
        }
        else if(þifre.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Lütfen þifrenizi giriniz.");
        }
        else if(kullanýcýAdý.equals("" ) && þifre.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Lütfen kullanýcý adýnýzý ve þifrenizi giriniz.");
        }
        
        else JOptionPane.showMessageDialog(rootPane, "KULLANICI ADI VEYA ÞÝFRE YANLIÞ");
    }//GEN-LAST:event_btnAnaMenü_GiriþYapActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YemekTarifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YemekTarifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YemekTarifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YemekTarifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YemekTarifi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnaMenü_AnaPanel;
    private javax.swing.JButton btnAnaMenü_GiriþYap;
    private javax.swing.JLabel lblAnaMenü_Hoþgeldiniz;
    private javax.swing.JLabel lblAnaMenü_Resimler;
    private javax.swing.JLabel lblAnaMenü_Resimler2;
    private javax.swing.JLabel lblAnaMenü_Resimler3;
    private javax.swing.JTextField txtAnaMenü_KullanýcýAdý;
    private javax.swing.JPasswordField txtAnaMenü_Þifre;
    // End of variables declaration//GEN-END:variables
}
